version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - mvn clean install
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 425008492849.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=425008492849.dkr.ecr.us-east-1.amazonaws.com/sudhiranjan-javatechie-registr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - DOCKER_CONTAINER_NAME=sudhiranjan-javatechie-registr
      - echo Repository URI is $REPOSITORY_URI
      - echo Container name is $DOCKER_CONTAINER_NAME
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Docker image built successfully

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Image pushed to ECR successfully
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Contents of imagedefinitions.json:
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json